---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-k8s-autopilot
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-autopilot
rules:
  # Allow to drain/uncordon
  #
  # NB: These permissions are tightly coupled to the bundled version of kubectl; the ones below
  # match https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/kubectl/cmd/drain.go
  #
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:     ["list", "get", "update", "patch", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs:     ["list","delete","get"]
  # deprecated Allow to get a list of PODs
  - apiGroups: ["extensions"]
    resources: ["daemonsets"]
    verbs:     ["get"]
  # Allow to get a list of PODs
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs:     ["get"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs:     ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-k8s-autopilot
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["azure-k8s-autopilot-leader"]
    verbs: ["get", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs:     ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-autopilot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-autopilot
subjects:
  - kind: ServiceAccount
    name: azure-k8s-autopilot
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: azure-k8s-autopilot
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: azure-k8s-autopilot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-k8s-autopilot
